package oscatalog

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/uplinkresearch/dsky/internal/appcatalog"
)

// Programs with Fedora and the RHEL family (docs/plan-linux-apps.md, step 4).
//
// The shape follows the Ubuntu side deliberately, because the decisions are
// the same ones: what the installer's own section can do, it does; what it
// cannot, a first-boot service does, logging to /var/log/dsky-apps.log and
// trying again at the next boot.
//
// One decision differs, and only in where it lands. DSKY's answers carry no
// account and no password, exactly as on Ubuntu Server — so Anaconda stops
// once, at its user screen, before it erases anything. That is the same single
// stop at the keyboard, in a different place on the screen.

// fedoraKickstartFile is where the generated kickstart goes in a workspace.
func fedoraKickstartFile(recipeID string) string {
	return "templates/dsky-fedora-" + recipeID + ".cfg.tmpl"
}

// writeFedoraKickstart writes the kickstart for a program list into the
// workspace and returns its workspace-relative path.
func writeFedoraKickstart(wsDir, recipeID string, ids []string) (string, error) {
	plan, err := appcatalog.ResolveFedora(ids)
	if err != nil {
		return "", err
	}
	rel := fedoraKickstartFile(recipeID)
	p := filepath.Join(wsDir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return "", err
	}
	// The picker's choices go in as a comment, so the recipe can be opened in
	// the install dialog again: the kickstart alone says what Fedora installs,
	// not which programs were picked.
	data := strings.Replace(fedoraKickstart(plan), "\n", "\n"+programsMarker+strings.Join(ids, " ")+"\n", 1)
	return rel, os.WriteFile(p, []byte(data), 0o644)
}

// fedoraKickstart renders the kickstart. The output is also a Go template
// (compose renders it as one), so it must never contain "{{".
func fedoraKickstart(plan appcatalog.FedoraPlan) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("# Generated by DSKY. The programs picked in DSKY, for Anaconda.")
	w("text")
	w("keyboard us")
	w("lang en_US.UTF-8")
	w("timezone UTC --utc")
	w("network --bootproto=dhcp --activate")
	// No account and no password in DSKY's answers, so Anaconda stops at its
	// user screen and asks. Same single stop as Ubuntu Server's interactive
	// identity section.
	w("clearpart --all --initlabel")
	w("autopart")
	w("firstboot --disable")
	w("services --enabled=sshd")
	if len(plan.Dnf) > 0 {
		// --ignoremissing, and it is load-bearing. Install media carries a
		// subset of Fedora's archive -- the Server DVD has vim-enhanced and
		// not vlc -- and %packages resolves against the media. Without this,
		// one name the DVD happens not to carry ends the whole install with
		// "No match for argument", having erased the disk first. With it, what
		// the media has goes on during setup and the rest is left to the
		// first-boot pass, which installs from Fedora's own repositories and
		// says in the log which ones it had to fetch.
		w("%%packages --ignoremissing")
		for _, p := range plan.Dnf {
			w("%s", p)
		}
		w("%%end")
	}
	if plan.FirstBoot() {
		script := base64.StdEncoding.EncodeToString([]byte(fedoraFirstBootScript(plan)))
		unit := base64.StdEncoding.EncodeToString([]byte(ubuntuFirstBootUnit))
		w("%%post")
		w("mkdir -p /usr/local/sbin /etc/systemd/system")
		w("echo %s | base64 -d > /usr/local/sbin/dsky-apps.sh", script)
		w("chmod 0755 /usr/local/sbin/dsky-apps.sh")
		w("echo %s | base64 -d > /etc/systemd/system/dsky-apps.service", unit)
		w("systemctl enable dsky-apps.service")
		w("%%end")
	}
	w("reboot")
	return b.String()
}

// fedoraFirstBootScript puts on what %packages cannot: Flathub apps, a
// vendor's rpm repository, and a published release binary — and confirms the
// packages it could, for the same reason the Ubuntu one does. A machine whose
// network came up late finishes its install quietly missing them.
func fedoraFirstBootScript(plan appcatalog.FedoraPlan) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("#!/bin/bash")
	w("# Generated by DSKY. Puts on the programs picked in DSKY that Anaconda's")
	w("# %%packages can't — Flathub apps, vendor repositories, published")
	w("# releases — and confirms the ones it can. Log: /var/log/dsky-apps.log")
	w("exec >>/var/log/dsky-apps.log 2>&1")
	w(`note() { echo "$(date -Is) $*"; }`)
	w(`note "first-boot programs starting"`)
	if hosts := fedoraProbeHosts(plan); len(hosts) > 0 {
		w(`for i in $(seq 1 90); do`)
		w(`  ready=1`)
		w(`  for h in %s; do`, strings.Join(hosts, " "))
		w(`    timeout 5 bash -c "</dev/tcp/$h/443" 2>/dev/null || { ready=0; break; }`)
		w(`  done`)
		w(`  [ "$ready" = 1 ] && break`)
		w(`  [ "$i" = 1 ] && note "waiting for the network ($h)"`)
		w(`  sleep 10`)
		w(`done`)
		w(`[ "$ready" = 1 ] || note "carrying on without reaching $h; what fails is tried again at the next boot"`)
	}
	w(`failed=0`)
	// rpm -q is the whole question on this side: unlike dpkg there is no
	// half-configured state to mistake for installed.
	w(`installed() { rpm -q "$1" >/dev/null 2>&1; }`)
	for _, pkg := range plan.Dnf {
		w(`if installed %s; then`, pkg)
		w(`  note "%s is installed"`, pkg)
		w(`elif dnf install -y -q %s; then`, pkg)
		w(`  note "installed %s (the installer did not)"`, pkg)
		w(`else`)
		w(`  note "FAILED %s"; failed=1`, pkg)
		w(`fi`)
	}
	for _, id := range plan.Repos {
		repo, ok := appcatalog.FedoraRepoByID(id)
		if !ok {
			w(`note "FAILED %s: DSKY does not know this repository"; failed=1`, id)
			continue
		}
		w(`if installed %s; then`, repo.Package)
		w(`  note "%s already installed"`, repo.Name)
		if repo.AMD64Only {
			w(`elif [ "$(uname -m)" != x86_64 ]; then`)
			w(`  note "SKIPPED %s: the vendor only publishes it for x86_64"`, repo.Name)
		}
		w(`else`)
		// gpgcheck stays on and the vendor's key is imported by name, so a
		// package that is not theirs does not install quietly.
		w(`  cat > /etc/yum.repos.d/%s.repo <<'REPOEOF'`, repo.ID)
		w(`[%s]`, repo.ID)
		w(`name=%s`, repo.Name)
		w(`baseurl=%s`, repo.BaseURL)
		w(`enabled=1`)
		w(`gpgcheck=1`)
		w(`repo_gpgcheck=0`)
		w(`gpgkey=%s`, repo.GPGKey)
		w(`REPOEOF`)
		w(`  if rpm --import %s && dnf install -y -q %s; then`, repo.GPGKey, repo.Package)
		w(`    note "installed %s"`, repo.Name)
		w(`  else`)
		w(`    note "FAILED %s"; failed=1`, repo.Name)
		w(`  fi`)
		w(`fi`)
	}
	if len(plan.Flatpaks) > 0 {
		w(`if ! command -v flatpak >/dev/null; then dnf install -y -q flatpak || { note "FAILED installing flatpak"; failed=1; }; fi`)
		w(`if command -v flatpak >/dev/null; then`)
		w(`  flatpak remote-add --system --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || { note "FAILED adding Flathub"; failed=1; }`)
		for _, id := range plan.Flatpaks {
			w(`  if flatpak install --system -y --noninteractive flathub %s; then note "installed %s"; else note "FAILED %s"; failed=1; fi`, id, id, id)
		}
		w(`fi`)
	}
	for _, id := range plan.Releases {
		rel, ok := appcatalog.UbuntuReleaseByID(id)
		if !ok {
			w(`note "FAILED %s: DSKY does not know this release"; failed=1`, id)
			continue
		}
		writeReleaseInstall(w, rel, "dnf install -y -q curl")
	}
	w(`if [ "$failed" = 0 ]; then`)
	w(`  mkdir -p /var/lib/dsky && touch /var/lib/dsky/apps-done`)
	w(`  note "first-boot programs done"`)
	w(`else`)
	w(`  note "first-boot programs finished with failures; trying again at the next boot"`)
	w(`fi`)
	w(`exit 0`)
	return b.String()
}

// fedoraProbeHosts are the hosts this plan has to reach before it is worth
// starting — only the ones it actually uses.
func fedoraProbeHosts(plan appcatalog.FedoraPlan) []string {
	var hosts []string
	if len(plan.Dnf) > 0 || len(plan.Repos) > 0 || len(plan.Flatpaks) > 0 {
		hosts = append(hosts, "mirrors.fedoraproject.org")
	}
	if len(plan.Flatpaks) > 0 {
		hosts = append(hosts, "dl.flathub.org")
	}
	for _, id := range plan.Repos {
		if repo, ok := appcatalog.FedoraRepoByID(id); ok {
			if h := repoHost(repo.GPGKey); h != "" {
				hosts = append(hosts, h)
			}
		}
	}
	if len(plan.Releases) > 0 {
		hosts = append(hosts, "github.com")
	}
	seen := map[string]bool{}
	out := hosts[:0]
	for _, h := range hosts {
		if !seen[h] {
			seen[h] = true
			out = append(out, h)
		}
	}
	return out
}

// writeLinuxAnswers writes whichever answers this entry's installer reads —
// Ubuntu's cloud-init autoinstall or Anaconda's kickstart — and returns their
// workspace-relative path. The two are never both written: an entry has one
// installer.
func writeLinuxAnswers(wsDir, recipeID string, e Entry, opts Options) (string, error) {
	if e.kickstartPrograms() {
		// Nothing to stage for drivers here: what Ubuntu's installer would be
		// asked to fetch, Fedora ships or does not.
		return writeFedoraKickstart(wsDir, recipeID, opts.Apps)
	}
	return writeUbuntuUserData(wsDir, recipeID, e, opts.Apps, opts.ThirdPartyDrivers)
}
