package recipe

// ModelInstallerScript is staged beside a first boot that runs a driver
// installer found for a particular computer model (Framework's driver
// bundles). It runs the installer only when Windows reports that model, and
// gives up on it after a time limit, so neither a stick carrying installers
// for several models nor a hung installer can stop first boot finishing.
//
// Its model rule is catalog.FrameworkModelMatches, written again in
// PowerShell: every word of the model this computer reports must appear in
// the pack's model name, and at least one of them must be a number. For ASUS
// it is catalog.ASUSModelMatches: the pack's model code is one piece of what
// the computer reports. Each is tested against the same names as its Go.
const ModelInstallerScript = `# Generated by DSKY. Runs a model's driver installer only on that model.
param(
  [Parameter(Mandatory = $true)][string]$Installer,
  [string]$Arguments = "",
  [Parameter(Mandatory = $true)][string]$Vendor,
  [Parameter(Mandatory = $true)][string]$Model,
  [int]$TimeoutMinutes = 90,
  [string]$ThisManufacturer = "",
  [string]$ThisModel = "",
  [switch]$CheckOnly
)

function Words([string]$s) {
  $s = $s.ToLowerInvariant()
  $s = [regex]::Replace($s, '([0-9])([a-z])', '$1 $2')
  $s = [regex]::Replace($s, '([a-z])([0-9])', '$1 $2')
  $v = $Vendor.ToLowerInvariant()
  return @([regex]::Split($s, '[^a-z0-9]+') | Where-Object { $_ -ne '' -and $_ -ne $v })
}

if (-not $ThisManufacturer) {
  $cs = Get-CimInstance Win32_ComputerSystem
  $ThisManufacturer = [string]$cs.Manufacturer
  $ThisModel = [string]$cs.Model
}
$tag = "[$Vendor $Model]"
if ($ThisManufacturer -notlike "*$Vendor*") {
  Write-Output "$tag skipped: this computer is made by '$ThisManufacturer'"
  exit 0
}
if ($Vendor -eq "asus") {
  # ASUS: the model code is one piece of what the computer reports,
  # "ASUS Zenbook 14 UX3405MA_UX3405MA" for the UX3405MA.
  $pieces = @([regex]::Matches($ThisModel.ToUpperInvariant(), '[A-Z0-9-]+') | ForEach-Object { $_.Value.Trim('-') })
  $fits = $pieces -contains $Model.ToUpperInvariant().Trim()
  $numeric = $true
} else {
  $want = Words $ThisModel
  $have = Words $Model
  $fits = $want.Count -gt 0
  $numeric = $false
  foreach ($w in $want) {
    if ($have -notcontains $w) { $fits = $false }
    if ($w -match '^[0-9]') { $numeric = $true }
  }
}
if (-not ($fits -and $numeric)) {
  Write-Output "$tag skipped: this computer is '$ThisModel'"
  exit 0
}
if ($CheckOnly) {
  Write-Output "$tag would run on '$ThisModel'"
  exit 0
}

Write-Output "$tag running $Installer $Arguments (at most $TimeoutMinutes minutes)"
if ($Arguments) {
  $p = Start-Process -FilePath $Installer -ArgumentList $Arguments -PassThru -WindowStyle Hidden
} else {
  $p = Start-Process -FilePath $Installer -PassThru -WindowStyle Hidden
}
if (-not $p.WaitForExit($TimeoutMinutes * 60 * 1000)) {
  Write-Output "$tag still running after $TimeoutMinutes minutes: stopping it so first boot can finish"
  & taskkill.exe /T /F /PID $p.Id | Out-Null
  exit 1460
}
Write-Output "$tag finished with exit code $($p.ExitCode)"
exit $p.ExitCode
`

// ModelInstallerScriptFile is the script as it is written to the stick, with
// Windows line endings.
func ModelInstallerScriptFile() string { return toCRLF(ModelInstallerScript) }

// ModelInstallerScriptName is the gate script's filename under Scripts\.
const ModelInstallerScriptName = "dsky-model-installer.ps1"

// ModelInstallerTimeoutMinutes bounds one model installer at first boot.
// Framework's bundle installs graphics, chipset and audio software one after
// another; an hour and a half is generous for that and still finite.
const ModelInstallerTimeoutMinutes = 90
