package recipe

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Context is what templates see: {{.Org.Name}}, {{.Vars.admin_user}}, plus
// the recipe itself for advanced templates.
type Context struct {
	Org    OrgInfo
	Vars   map[string]string
	Recipe *Recipe
}

// OrgInfo identifies the workspace's organization (from workspace.yaml).
type OrgInfo struct {
	Name string
	ID   string
}

func xmlEscape(s string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(s))
	return b.String()
}

// RenderTemplate renders a workspace template file. Missing keys are errors:
// silently-empty unattend fields produce media that stalls at OOBE.
func RenderTemplate(path string, ctx Context) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	t, err := template.New(filepath.Base(path)).
		Funcs(template.FuncMap{"xml": xmlEscape}).
		Option("missingkey=error").
		Parse(string(b))
	if err != nil {
		return "", fmt.Errorf("template %s: %w", path, err)
	}
	var out strings.Builder
	if err := t.Execute(&out, ctx); err != nil {
		return "", fmt.Errorf("template %s: %w", path, err)
	}
	return out.String(), nil
}

// GenerateEICfg renders sources/ei.cfg (CRLF, as Windows media ships it).
func GenerateEICfg(e *EICfg) string {
	channel := e.Channel
	if channel == "" {
		channel = "Retail"
	}
	vl := "0"
	if e.VL {
		vl = "1"
	}
	return toCRLF(fmt.Sprintf("[EditionID]\n%s\n[Channel]\n%s\n[VL]\n%s\n", e.Edition, channel, vl))
}

// ResolvedDrivers is the driver material the `drivers` firstboot step
// installs, resolved by the compose stage to on-stick filenames.
type ResolvedDrivers struct {
	// Cabs are expand-then-sweep packs: the .cab filename staged directly
	// under Scripts/, expanded into Scripts/Drivers/<Dir>/ at boot.
	Cabs []struct {
		File string // e.g. intel-sst-10.29.0.12571.cab
		Dir  string // e.g. intel-sst
	}
	// Extracts are vendor self-extracting packs (Dell/Lenovo/HP): the exe
	// staged under Scripts/, unpacked into Scripts/Drivers/<Dir>/ at boot
	// with Args ({dir} substituted), then swept.
	Extracts []struct {
		File string
		Dir  string
		Args []string
	}
	// HasSweepable is true when any INF material lands under
	// Scripts/Drivers/ (inf-dir packs, expanded cabs, extracted packs).
	HasSweepable bool
	// Exes are vendor silent installers staged under Scripts/.
	Exes []struct {
		File string
		Args []string
		Log  string
		// OnlyVendor/OnlyModel, when set, run it through the model gate
		// script (ModelInstallerScript) instead of directly.
		OnlyVendor string
		OnlyModel  string
	}
}

// GenerateFirstboot builds the first-boot .cmd from ordered steps —
// the generalized install-agent.cmd. resolveRef maps a payload/source ref to
// its staged filename under Scripts\.
func GenerateFirstboot(r *Recipe, drivers ResolvedDrivers, resolveRef func(ref string) (string, error)) (string, error) {
	w := r.Windows
	var b strings.Builder
	line := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}
	logNote := func(what string) {
		line(`echo [%%date%% %%time%%] %s exited with %%errorlevel%% >> "%%LOG%%"`, what)
	}

	line("@echo off")
	line("rem Generated by DSKY - recipe %s. Edit the recipe, not this file.", r.ID)
	line("setlocal")
	line(`set SCRIPTS=C:\Windows\Setup\Scripts`)
	line(`set LOG=%%SCRIPTS%%\%s`, w.Firstboot.Log)
	line("")
	line(`echo [%%date%% %%time%%] first-boot script starting >> "%%LOG%%"`)

	// Domain join is checked before anything else runs, and it is not optional
	// or configurable.
	//
	// Windows Setup does not report a failed domain join. It carries on, and
	// the machine finishes installing into a workgroup looking entirely
	// correct — nobody inspects a fresh machine for domain membership, so this
	// surfaces days later as a failed login, somewhere else, to someone who
	// was not there. The one moment the evidence exists is now, so capture it
	// now and leave it where a technician will trip over it.
	if w.Domain.Enabled() {
		line("")
		line(`rem --- did the domain join actually happen? ---`)
		line(`rem Setup does not report a failed join; it installs into a workgroup`)
		line(`rem and says nothing. So check, and leave the logs somewhere obvious.`)
		line(`set JOINED=`)
		line(`for /f %%%%d in ('powershell -NoProfile -Command ` +
			`"(Get-CimInstance Win32_ComputerSystem).PartOfDomain" 2^>nul') do set JOINED=%%%%d`)
		line(`if /i "%%JOINED%%"=="True" (`)
		line(`  echo [%%date%% %%time%%] domain join OK: %%USERDOMAIN%% >> "%%LOG%%"`)
		line(`) else (`)
		line(`  echo [%%date%% %%time%%] DOMAIN JOIN FAILED - this machine is in a workgroup >> "%%LOG%%"`)
		line(`  copy /y C:\Windows\debug\netsetup.log C:\DOMAIN-JOIN-FAILED-netsetup.log >nul 2>&1`)
		line(`  copy /y C:\Windows\Panther\UnattendGC\setuperr.log C:\DOMAIN-JOIN-FAILED-setuperr.log >nul 2>&1`)
		line(`  copy /y C:\Windows\Panther\UnattendGC\setupact.log C:\DOMAIN-JOIN-FAILED-setupact.log >nul 2>&1`)
		line(`)`)
	}

	steps := w.Firstboot.Steps
	if len(steps) == 0 {
		steps = []Step{{Drivers: true}}
	}
	// A debloat spec without an explicit step runs right after drivers
	// (before agents, so their installs land on the cleaned system).
	if w.Debloat.Enabled() {
		has := false
		for _, s := range steps {
			if s.Debloat {
				has = true
			}
		}
		if !has {
			at := 0
			for i, s := range steps {
				if s.Drivers {
					at = i + 1
				}
			}
			steps = append(steps[:at:at], append([]Step{{Debloat: true}}, steps[at:]...)...)
		}
	}
	// Programs install after drivers (they need the network the NIC driver
	// just enabled) and after debloat (so app removal cannot race a fresh
	// install), but before agents.
	if w.Apps.Enabled() {
		has := false
		for _, s := range steps {
			if s.Apps {
				has = true
			}
		}
		if !has {
			at := 0
			for i, s := range steps {
				if s.Drivers || s.Debloat {
					at = i + 1
				}
			}
			steps = append(steps[:at:at], append([]Step{{Apps: true}}, steps[at:]...)...)
		}
	}
	for _, s := range steps {
		line("")
		switch {
		case s.Drivers:
			for n, cab := range drivers.Cabs {
				line(`rem --- expand %s so the pnputil sweep below installs its drivers ---`, cab.File)
				line(`if not exist "%%SCRIPTS%%\%s" goto :expand_%d_done`, cab.File, n)
				line(`mkdir "%%SCRIPTS%%\Drivers\%s" 2>nul`, cab.Dir)
				line(`expand "%%SCRIPTS%%\%s" -F:* "%%SCRIPTS%%\Drivers\%s" > nul`, cab.File, cab.Dir)
				line(`echo [%%date%% %%time%%] %s expand exited with %%errorlevel%% >> "%%LOG%%"`, cab.Dir)
				line(`:expand_%d_done`, n)
			}
			for n, ex := range drivers.Extracts {
				dest := `%SCRIPTS%\Drivers\` + ex.Dir
				expand := func(list []string) string {
					out := make([]string, len(list))
					for i, a := range list {
						out[i] = strings.ReplaceAll(a, "{dir}", dest)
					}
					return strings.Join(out, " ")
				}
				// Success is "did .inf files appear", never the exit code: an
				// HP EliteBook pack given the wrong switch style printed its
				// usage text, extracted nothing and exited 0. HP changed
				// SoftPaq switches from -pdf -e -s -f"dir" to /s /e /f dir,
				// and sticks meet both generations, so the other style is the
				// retry. goto, not (blocks): %errorlevel% inside parentheses
				// expands when the block is parsed, which is how the old
				// script logged "exited with 0" for that failed extract.
				line(`rem --- unpack vendor driver pack %s so the pnputil sweep installs it ---`, ex.File)
				line(`if not exist "%%SCRIPTS%%\%s" goto :extract_%d_done`, ex.File, n)
				line(`mkdir "%s" 2>nul`, dest)
				line(`"%%SCRIPTS%%\%s" %s`, ex.File, expand(ex.Args))
				line(`echo [%%date%% %%time%%] %s extract exited with %%errorlevel%% >> "%%LOG%%"`, ex.Dir)
				line(`dir /s /b "%s\*.inf" >nul 2>&1`, dest)
				line(`if not errorlevel 1 goto :extract_%d_done`, n)
				alt := expand(alternateExtract(ex.Args))
				line(`echo [%%date%% %%time%%] %s: no driver files appeared, retrying with %s >> "%%LOG%%"`, ex.Dir, alt)
				line(`"%%SCRIPTS%%\%s" %s`, ex.File, alt)
				line(`echo [%%date%% %%time%%] %s retry exited with %%errorlevel%% >> "%%LOG%%"`, ex.Dir)
				line(`dir /s /b "%s\*.inf" >nul 2>&1`, dest)
				line(`if errorlevel 1 echo [%%date%% %%time%%] FAILED %s: no driver files extracted from %s >> "%%LOG%%"`, ex.Dir, ex.File)
				line(`:extract_%d_done`, n)
			}
			if drivers.HasSweepable {
				line(`rem --- pnputil installs only what matches this hardware, so packs for`)
				line(`rem --- multiple machine models can share one stick. Skipped when no`)
				line(`rem --- pack yielded drivers: on nothing it exits 87 and muddies the log ---`)
				line(`dir /s /b "%%SCRIPTS%%\Drivers\*.inf" >nul 2>&1`)
				line(`if errorlevel 1 goto :no_driver_files`)
				line(`pnputil /add-driver "%%SCRIPTS%%\Drivers\*.inf" /subdirs /install >> "%%LOG%%" 2>&1`)
				line(`echo [%%date%% %%time%%] pnputil exited with %%errorlevel%% >> "%%LOG%%"`)
				line(`goto :driver_sweep_done`)
				line(`:no_driver_files`)
				line(`echo [%%date%% %%time%%] no driver files to install >> "%%LOG%%"`)
				line(`:driver_sweep_done`)
			}
			for n, exe := range drivers.Exes {
				args := strings.Join(exe.Args, " ")
				if exe.Log != "" {
					args = strings.ReplaceAll(args, "{log}", `%SCRIPTS%\`+exe.Log)
				}
				if exe.OnlyModel != "" {
					line(`rem --- %s driver installer for %s: runs only on that model, for at most %d minutes ---`,
						exe.OnlyVendor, exe.OnlyModel, ModelInstallerTimeoutMinutes)
					line(`if not exist "%%SCRIPTS%%\%s" goto :exe_%d_done`, exe.File, n)
					line(`powershell -NoProfile -ExecutionPolicy Bypass -File "%%SCRIPTS%%\%s" -Installer "%%SCRIPTS%%\%s" -Arguments "%s" -Vendor "%s" -Model "%s" -TimeoutMinutes %d >> "%%LOG%%" 2>&1`,
						ModelInstallerScriptName, exe.File, args, exe.OnlyVendor, exe.OnlyModel, ModelInstallerTimeoutMinutes)
					line(`echo [%%date%% %%time%%] %s exited with %%errorlevel%% >> "%%LOG%%"`, exe.File)
					line(`:exe_%d_done`, n)
					continue
				}
				line(`rem --- vendor driver installer %s ---`, exe.File)
				line(`if not exist "%%SCRIPTS%%\%s" goto :exe_%d_done`, exe.File, n)
				line(`"%%SCRIPTS%%\%s" %s`, exe.File, args)
				line(`echo [%%date%% %%time%%] %s exited with %%errorlevel%% >> "%%LOG%%"`, exe.File)
				line(`:exe_%d_done`, n)
			}
		case s.Debloat:
			line(`rem --- debloat: strip consumer apps, ads, Copilot, widgets (preset %s) ---`, w.Debloat.Preset)
			line(`powershell -NoProfile -ExecutionPolicy Bypass -File "%%SCRIPTS%%\debloat.ps1" >> "%%LOG%%" 2>&1`)
			logNote("debloat")
		case s.Apps:
			line(`rem --- install %d program(s) with winget; needs the network, see apps.log ---`, len(w.Apps.Winget))
			line(`powershell -NoProfile -ExecutionPolicy Bypass -File "%%SCRIPTS%%\apps.ps1" >> "%%LOG%%" 2>&1`)
			logNote("apps")
		case s.Wait > 0:
			secs := int(s.Wait.Seconds())
			line(`rem --- settle for %ds (freshly-driver'd NICs need a moment before agents) ---`, secs)
			line(`ping -n %d 127.0.0.1 > nul`, secs+1)
		case s.MSI != nil:
			file, err := resolveRef(s.MSI.Ref)
			if err != nil {
				return "", err
			}
			logName := s.MSI.Log
			if logName == "" {
				logName = strings.TrimSuffix(file, filepath.Ext(file)) + "-msi.log"
			}
			line(`rem --- install %s ---`, file)
			args := strings.Join(s.MSI.Args, " ")
			if args == "" {
				args = "/qn"
			}
			line(`msiexec /i "%%SCRIPTS%%\%s" %s /l*v "%%SCRIPTS%%\%s"`, file, args, logName)
			logNote("msiexec")
		case s.Exe != nil:
			file, err := resolveRef(s.Exe.Ref)
			if err != nil {
				return "", err
			}
			line(`rem --- run %s ---`, file)
			line(`"%%SCRIPTS%%\%s" %s`, file, strings.Join(s.Exe.Args, " "))
			logNote(file)
		case s.Cmd != "":
			line("%s", s.Cmd)
		}
	}

	line("")
	line(`echo [%%date%% %%time%%] first-boot script done >> "%%LOG%%"`)

	// The status screen runs last, and deliberately AFTER the done line: the
	// check it runs treats a log with no completion as "first boot is still
	// going", so calling it any earlier would paint "still running" every
	// time and never show a real result.
	//
	// Nobody has to remember to run it, which is the whole point — a bench of
	// machines paints itself and the technician reads the room.
	if w.StatusScreen.Enabled() {
		line("")
		line(`rem --- check this machine against the build and show the result ---`)
		line(`rem Paints the lock screen and desktop green or red so a bench of`)
		line(`rem machines can be read without logging into each one.`)
		line(`powershell -NoProfile -ExecutionPolicy Bypass -File "%%SCRIPTS%%\verify.ps1" >> "%%LOG%%" 2>&1`)
		line(`echo [%%date%% %%time%%] status screen set (exit %%errorlevel%%) >> "%%LOG%%"`)
	}
	line("endlocal")
	return toCRLF(b.String()), nil
}

// alternateExtract is the retry switch set for a vendor pack extractor that
// produced no drivers: HP SoftPaqs come in a -pdf -e -s generation and a
// /s /e /f generation, and the wrong style prints usage and exits 0.
func alternateExtract(args []string) []string {
	for _, a := range args {
		if strings.HasPrefix(a, "-") {
			return []string{"/s", "/e", "/f", `"{dir}"`}
		}
	}
	return []string{"-pdf", "-e", "-s", `-f"{dir}"`}
}

// toCRLF normalizes to CRLF line endings — cmd.exe misparses LF-only batch
// files in several constructs, and ei.cfg ships CRLF on real media.
func toCRLF(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\n", "\r\n")
}
