package recipe

import (
	"fmt"
	"strings"
)

// The post-install check.
//
// Everything this tool promises is decided at build time and delivered at
// first boot, with hours and a reinstall in between. Up to now the only way to
// know it worked was to look: Device Manager for yellow bangs, a Start menu
// for the programs, a domain login for the join. That is fine for one machine
// and useless for twenty, and it is exactly where a silent failure lives —
// nobody audits a machine that looks installed.
//
// So the build writes down what it intended, as a script that checks it. It is
// generated rather than shipped because only the build knows what was asked
// for, and it is PowerShell rather than a command in this tool because the
// machine it runs on has just been imaged and has nothing installed on it.
//
// Read-only. It reports and changes nothing, so running it twice, or on the
// wrong machine, costs nothing but the output.

// GenerateVerifyPS renders the post-install verification script.
//
// resolveRef maps a payload ref to its staged filename, the same as the
// first-boot generator, so a custom installer can be checked by the name it
// actually landed under.
func GenerateVerifyPS(r *Recipe, drivers ResolvedDrivers, resolveRef func(ref string) (string, error)) string {
	w := r.Windows
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p(`# Generated by DSKY - recipe %s.`, r.ID)
	p(`# Checks this machine against what the build intended. Read-only.`)
	p(`#`)
	p(`#   powershell -ExecutionPolicy Bypass -File C:\Windows\Setup\Scripts\verify.ps1`)
	p(`#`)
	p(`# Run it AFTER first boot has finished its work - installing programs takes`)
	p(`# a few minutes and needs the network. Run too early it exits 2 and says so.`)
	p(`#`)
	p(`# Exit codes:  0 matches the build   1 does not match   2 first boot still running`)
	p(``)
	p(`$ErrorActionPreference = 'SilentlyContinue'`)
	p(`$pass = 0; $fail = 0; $warn = 0`)
	p(`$script:failures = @()`)
	p(`function OK   ($m) { $script:pass++; Write-Host ("  [ OK ] " + $m) -ForegroundColor Green }`)
	p(`function FAIL ($m) { $script:fail++; $script:failures += $m; Write-Host ("  [FAIL] " + $m) -ForegroundColor Red }`)
	p(`function WARN ($m) { $script:warn++; Write-Host ("  [warn] " + $m) -ForegroundColor Yellow }`)
	p(`function Head ($m) { Write-Host ""; Write-Host $m -ForegroundColor Cyan }`)
	if w.StatusScreen.Enabled() {
		statusScreenPS(w.StatusScreen, p)
	}
	p(``)
	p(`Write-Host "DSKY post-install check - recipe %s" -ForegroundColor White`, r.ID)
	p(`Write-Host ("machine: " + $env:COMPUTERNAME + "   " + (Get-CimInstance Win32_ComputerSystem).Model)`)
	p(`$scripts = 'C:\Windows\Setup\Scripts'`)
	p(``)

	// ── First boot ───────────────────────────────────────────────────────
	// Everything else depends on this having run at all.
	p(`Head "First boot"`)
	p(`$fb = Join-Path $scripts '%s'`, firstbootLog(w))
	p(`if (Test-Path $fb) {`)
	p(`  $log = Get-Content $fb -Raw`)
	p(`  OK "first-boot script ran ($fb)"`)
	p(`  if ($log -match 'done') { OK "first-boot script reached the end" }`)
	p(`  else {`)
	// Told apart by how recently the log was touched. Installing programs
	// takes minutes and needs the network, so someone running this at the
	// first logon prompt would otherwise get a red report that only means
	// "not finished yet" — and a check that cries wolf gets ignored.
	p(`    $age = (Get-Date) - (Get-Item $fb).LastWriteTime`)
	p(`    if ($age.TotalMinutes -lt 10) {`)
	p(`      Write-Host ""`)
	p(`      Write-Host "  FIRST BOOT IS STILL RUNNING - checked too early." -ForegroundColor Yellow`)
	p(`      Write-Host ("  The log was written " + [int]$age.TotalSeconds + "s ago. Installing programs takes") -ForegroundColor Yellow`)
	p(`      Write-Host "  a few minutes and needs the network. Wait for it to finish, then run this again." -ForegroundColor Yellow`)
	p(`      Write-Host ("  Watch it:  Get-Content '" + $fb + "' -Wait") -ForegroundColor Yellow`)
	p(`      exit 2`)
	p(`    }`)
	p(`    FAIL ("first-boot log has no completion line and has not been written to for " + [int]$age.TotalMinutes + " minutes - it stopped partway")`)
	p(`  }`)
	// Nonzero exit codes are logged per step by the first-boot script.
	p(`  $bad = [regex]::Matches($log, '(?m)^.*exited with ([1-9]\d*)\s*$')`)
	p(`  if ($bad.Count -gt 0) { foreach ($m in $bad) { WARN ("a step reported failure: " + $m.Value.Trim()) } }`)
	p(`  else { OK "no step reported a nonzero exit code" }`)
	p(`} else { FAIL "no first-boot log at $fb - the script never ran" }`)
	p(``)

	// ── Drivers ──────────────────────────────────────────────────────────
	// The check that matters on a freshly imaged machine, and the one people
	// do by eye in Device Manager.
	p(`Head "Devices"`)
	p(`$prob = Get-CimInstance Win32_PnPEntity | Where-Object { $_.ConfigManagerErrorCode -ne 0 }`)
	p(`if ($prob) {`)
	p(`  FAIL ("" + $prob.Count + " device(s) have a problem:")`)
	p(`  foreach ($d in $prob) { Write-Host ("         " + $d.Name + "  [code " + $d.ConfigManagerErrorCode + "]  " + $d.DeviceID) }`)
	p(`} else { OK "every device has a working driver (no problem codes)" }`)
	// Vendor installers run as executables and leave no INF material, so they
	// are checked by their own logs; only sweepable packs land under Drivers/.
	if drivers.HasSweepable {
		p(`$staged = Join-Path $scripts 'Drivers'`)
		p(`if (Test-Path $staged) { OK ("driver material was staged: " + (Get-ChildItem $staged -Directory).Count + " pack(s) under Drivers\") }`)
		p(`else { WARN "no Drivers folder on the installed system - it may have been cleaned up after the sweep" }`)
	}
	for _, e := range drivers.Exes {
		log := e.Log
		if log == "" {
			log = strings.TrimSuffix(e.File, ".exe") + ".log"
		}
		p(`if (Test-Path (Join-Path $scripts '%s')) { OK "vendor driver installer %s ran (log present)" }`, log, e.File)
		p(`else { WARN "no log from vendor driver installer %s" }`, e.File)
	}
	p(``)

	// ── Account and edition ──────────────────────────────────────────────
	p(`Head "Windows"`)
	p(`$os = Get-CimInstance Win32_OperatingSystem`)
	p(`Write-Host ("         " + $os.Caption + " (" + $os.Version + ")")`)
	if w.EICfg != nil && w.EICfg.Edition != "" {
		p(`if ($os.Caption -match '%s') { OK "edition is %s as requested" }`, editionMatch(w.EICfg.Edition), w.EICfg.Edition)
		p(`else { FAIL "expected edition %s, got: $($os.Caption)" }`, w.EICfg.Edition)
	}
	// Server has no ei.cfg: the edition came from an image index, and an
	// index that pointed at the wrong image is exactly what this catches.
	if w.Unattend != nil {
		if ed := w.Unattend.Vars["server_edition"]; ed != "" {
			p(`if ($os.Caption -match '%s') { OK "edition is Server %s as requested" }`, serverEditionMatch(ed), ed)
			p(`else { FAIL "expected Server %s, got: $($os.Caption)" }`, ed)
			// Caption reads the same for Core and Desktop Experience, so the
			// half of the choice that Caption cannot show is read here.
			// The recipe states it outright now that Server Core is an entry
			// of its own rather than an edition. Older recipes carried it in
			// the edition name -- "Standard Core", "Standard (Server Core)"
			// -- and are still read that way.
			want := "Server"
			if strings.Contains(ed, "Core") {
				want = "Server Core"
			}
			if t := w.Unattend.Vars["server_installation_type"]; t != "" {
				want = t
			}
			p(`$it = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').InstallationType`)
			p(`if ($it -eq '%s') { OK "installation type is %s as requested" }`, want, want)
			p(`else { FAIL "expected %s, got: $it" }`, want)
		}
	}
	if w.Unattend != nil {
		if user := w.Unattend.Vars["admin_user"]; user != "" && accountMode(w) == "local" {
			p(`if (Get-LocalUser -Name '%s' -ErrorAction SilentlyContinue) { OK "local account '%s' exists" }`, user, user)
			p(`else { FAIL "local account '%s' was not created" }`, user)
		}
	}
	p(``)

	// ── Domain ───────────────────────────────────────────────────────────
	// The silent one: Setup does not report a failed join, it just carries on.
	if w.Domain.Enabled() {
		p(`Head "Domain"`)
		p(`$cs = Get-CimInstance Win32_ComputerSystem`)
		p(`if ($cs.PartOfDomain) {`)
		if d := w.Domain; !d.Offline() && d.Join != "" && !strings.Contains(d.Join, "${var:") {
			p(`  if ($cs.Domain -eq '%s') { OK "joined %s" }`, d.Join, d.Join)
			p(`  else { FAIL ("joined the wrong domain: " + $cs.Domain + ", expected %s") }`, d.Join)
		} else {
			p(`  OK ("joined " + $cs.Domain)`)
		}
		// A join that succeeded but left a broken trust is the failure mode an
		// offline blob hits when something else renames the machine.
		p(`  if (Test-ComputerSecureChannel -ErrorAction SilentlyContinue) { OK "secure channel to the domain is healthy" }`)
		p(`  else { FAIL "domain trust relationship is broken - the machine name may not match its computer account" }`)
		p(`} else {`)
		p(`  FAIL ("NOT joined to a domain - this machine is in workgroup " + $cs.Workgroup)`)
		p(`  Write-Host "         Windows Setup does not report a failed join; it installs into a workgroup." -ForegroundColor Yellow`)
		p(`  foreach ($l in @('C:\DOMAIN-JOIN-FAILED-netsetup.log','C:\DOMAIN-JOIN-FAILED-setuperr.log','C:\DOMAIN-JOIN-FAILED-setupact.log')) {`)
		p(`    if (Test-Path $l) { Write-Host ("         evidence: " + $l) -ForegroundColor Yellow }`)
		p(`  }`)
		p(`}`)
		p(``)
	}

	// ── Programs ─────────────────────────────────────────────────────────
	if w.Apps.Enabled() || len(customInstallers(w, resolveRef)) > 0 {
		p(`Head "Programs"`)
		// One registry sweep, then match against it: querying winget per
		// package is slow and misses anything winget did not install.
		p(`$installed = @()`)
		p(`foreach ($k in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',`)
		p(`                 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',`)
		p(`                 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*')) {`)
		p(`  $installed += Get-ItemProperty $k | Where-Object { $_.DisplayName } | ForEach-Object { $_.DisplayName }`)
		p(`}`)
		p(`Write-Host ("         " + $installed.Count + " installed programs found")`)
		// Guarded: this block is also reached by a recipe that stages its own
		// installer and asks for no winget packages at all — which is the
		// ordinary MSP case, an agent and nothing else.
		if w.Apps.Enabled() {
			for _, pkg := range w.Apps.Winget {
				hint := wingetDisplayHint(pkg)
				p(`if ($installed -match '%s') { OK "%s is installed" } else { FAIL "%s is NOT installed" }`, hint, pkg, pkg)
			}
		}
		for _, c := range customInstallers(w, resolveRef) {
			p(`if (Test-Path (Join-Path $scripts '%s')) { OK "your installer %s was staged on the media" }`, c, c)
			p(`else { WARN "your installer %s is not in $scripts - it may have been cleaned up" }`, c)
		}
		p(`Write-Host "         (check any missing program in apps.log - winget needs the network at first boot)" -ForegroundColor DarkGray`)
		p(``)
	}

	p(`Head "Result"`)
	p(`Write-Host ("  passed $pass   failed $fail   warnings $warn")`)
	if w.StatusScreen.Enabled() {
		p(`Set-StatusScreen -Failed $fail -Warned $warn`)
	}
	p(`if ($fail -gt 0) { Write-Host "  THIS MACHINE DOES NOT MATCH THE BUILD" -ForegroundColor Red; exit 1 }`)
	p(`Write-Host "  matches what the build intended" -ForegroundColor Green`)
	p(`exit 0`)
	return toCRLF(b.String())
}

// statusScreenPS is the part that paints the answer onto the machine.
//
// The check already knows what failed; a technician walking a bench of twenty
// machines does not, and cannot without sitting down at each one. So the
// result goes where it can be read from the doorway: the lock screen and the
// desktop, with the failures listed on it rather than a bare red cross —
// knowing WHICH machine to pick up is only half of it.
//
// Drawn at runtime rather than shipped as artwork, because the failure list is
// not known until the check runs, and because this has to work for an operator
// who supplied no images at all.
func statusScreenPS(s *StatusScreen, p func(string, ...any)) {
	p(``)
	p(`function New-StatusImage {`)
	// The colour components are typed: passed untyped, PowerShell cannot pick
	// the three-argument FromArgb overload and the background silently stays
	// black, which is neither green nor red and tells a technician nothing.
	p(`  param([string]$Path, [string]$Title, [string[]]$Lines, [int]$R, [int]$G, [int]$B)`)
	p(`  Add-Type -AssemblyName System.Drawing`)
	// 1920x1080 regardless of the panel: Windows scales the lock screen
	// image, and a fixed size keeps the text legible on the 1366x768 laptops
	// this lands on as often as not.
	p(`  $w = 1920; $h = 1080`)
	p(`  $bmp = New-Object System.Drawing.Bitmap $w, $h`)
	// $gfx, not $g: PowerShell variable names are case-insensitive, so $g and
	// the [int]$G colour parameter are the SAME variable — the Graphics object
	// gets cast to Int32 and every draw call after it fails.
	p(`  $gfx = [System.Drawing.Graphics]::FromImage($bmp)`)
	p(`  $gfx.SmoothingMode = 'AntiAlias'`)
	p(`  $gfx.TextRenderingHint = 'ClearTypeGridFit'`)
	p(`  $gfx.Clear([System.Drawing.Color]::FromArgb($R, $G, $B))`)
	p(`  $white = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::White)`)
	p(`  $fTitle = New-Object System.Drawing.Font 'Segoe UI', 96, ([System.Drawing.FontStyle]::Bold)`)
	p(`  $fBody  = New-Object System.Drawing.Font 'Segoe UI', 28`)
	p(`  $fSmall = New-Object System.Drawing.Font 'Segoe UI', 22`)
	p(`  $gfx.DrawString($Title, $fTitle, $white, 120, 130)`)
	p(`  $y = 320`)
	p(`  foreach ($l in $Lines) {`)
	// Bounded: a machine with thirty broken devices must not push the name
	// and time off the bottom of the screen.
	p(`    if ($y -gt 830) { $gfx.DrawString("...and more - run verify.ps1 for the full list", $fSmall, $white, 120, $y); break }`)
	p(`    $gfx.DrawString($l, $fBody, $white, 120, $y); $y += 46`)
	p(`  }`)
	p(`  $stamp = "$env:COMPUTERNAME    $(Get-Date -Format 'yyyy-MM-dd HH:mm')"`)
	p(`  $gfx.DrawString($stamp, $fSmall, $white, 120, 950)`)
	p(`  $gfx.DrawString("C:\Windows\Setup\Scripts\verify.ps1 for detail", $fSmall, $white, 120, 990)`)
	p(`  $gfx.Dispose()`)
	p(`  $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Jpeg)`)
	p(`  $bmp.Dispose()`)
	p(`}`)
	p(``)
	p(`function Set-StatusScreen {`)
	p(`  param([int]$Failed, [int]$Warned)`)
	p(`  try {`)
	p(`    $dir = 'C:\ProgramData\DSKY'`)
	p(`    if (-not (Test-Path $dir)) { [void](mkdir $dir) }`)
	p(`    $img = Join-Path $dir 'status.jpg'`)
	p(`    if ($Failed -gt 0) {`)
	p(`      $lines = @("$Failed check(s) failed:") + ($script:failures | Select-Object -First 10)`)
	p(`      New-StatusImage -Path $img -Title 'IMAGING FAILED' -Lines $lines -R 155 -G 25 -B 25`)
	p(`    } else {`)
	if path, ref := s.SuccessImage(); path != "" || ref != "" {
		// An operator's own artwork is used verbatim when it is there, and
		// falls back rather than failing when it is not: a missing logo must
		// not cost you the signal.
		p(`      $logo = Join-Path 'C:\Windows\Setup\Scripts' '%s'`, statusImageName(s))
		p(`      if (Test-Path $logo) { Copy-Item $logo $img -Force }`)
		p(`      else {`)
		p(`        $lines = @("This machine matches the build.")`)
		p(`        if ($Warned -gt 0) { $lines += "$Warned warning(s) - see verify.ps1" }`)
		p(`        New-StatusImage -Path $img -Title 'READY' -Lines $lines -R 20 -G 105 -B 60`)
		p(`      }`)
	} else {
		p(`      $lines = @("This machine matches the build.")`)
		p(`      if ($Warned -gt 0) { $lines += "$Warned warning(s) - see verify.ps1" }`)
		p(`      New-StatusImage -Path $img -Title 'READY' -Lines $lines -R 20 -G 105 -B 60`)
	}
	p(`    }`)
	p(``)
	// PersonalizationCSP rather than the Personalization policy key: the
	// policy one is Enterprise/Education only and does nothing on the Pro
	// these machines ship with.
	p(`    $csp = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP'`)
	p(`    if (-not (Test-Path $csp)) { [void](New-Item -Path $csp -Force) }`)
	p(`    foreach ($n in @('LockScreenImagePath','LockScreenImageUrl')) {`)
	p(`      New-ItemProperty -Path $csp -Name $n -Value $img -PropertyType String -Force | Out-Null`)
	p(`    }`)
	p(`    New-ItemProperty -Path $csp -Name 'LockScreenImageStatus' -Value 1 -PropertyType DWord -Force | Out-Null`)
	// The desktop too: first boot ends logged in, so the lock screen alone
	// would show nothing until the machine locked itself.
	p(`    Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name Wallpaper -Value $img`)
	p(`    Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name WallpaperStyle -Value 10`)
	p(`    rundll32.exe user32.dll, UpdatePerUserSystemParameters 1, True`)
	if !s.Keep {
		// The screen answers one question for one person, once. The machine
		// is then shut down and shipped, and whoever opens the box must not
		// find the imaging bench's signal as their wallpaper — least of all a
		// red one.
		//
		// Cleared at the next startup rather than at the next logon: a
		// startup task runs before the logon screen is drawn, so the end
		// user never sees it at all. A RunOnce covers the desktop as well,
		// because the wallpaper lives in the user's own hive where a task
		// running as SYSTEM cannot reach it.
		// The path is fixed and has no spaces, so it is passed unquoted.
		// Quoting it would be worse, not safer: PowerShell wraps a native
		// command's argument in quotes of its own, and the result is the
		// nested "cmd /c "C:\...cmd"" that schtasks then mis-parses.
		p(`    $clear = 'C:\Windows\Setup\Scripts\clear-status-screen.cmd'`)
		p(`    if (Test-Path $clear) {`)
		p(`      schtasks /Create /F /TN DSKYClearStatusScreen /SC ONSTART /RU SYSTEM /RL HIGHEST /TR ('cmd /c ' + $clear) | Out-Null`)
		p(`      New-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce' ` +
			`-Name 'DSKYClearStatusScreen' -Value ('cmd /c ' + $clear) -PropertyType String -Force | Out-Null`)
		p(`      Write-Host "  it clears itself on the next boot (clear-status-screen.cmd to do it now)"`)
		p(`    }`)
	} else {
		p(`    Write-Host "  kept until clear-status-screen.cmd is run (status_screen.keep is set)"`)
	}
	p(`    Write-Host "  status screen set: $img"`)
	p(`  } catch {`)
	// Never fatal. The screen is a convenience; the report and the exit code
	// are the actual answer, and losing the paint job must not lose those.
	p(`    Write-Host ("  could not set the status screen: " + $_.Exception.Message) -ForegroundColor Yellow`)
	p(`  }`)
	p(`}`)
	p(``)
}

// GenerateClearStatusScreen puts the machine back to the Windows default.
//
// Run three ways, and it has to be safe in all of them: by a startup task as
// SYSTEM, by RunOnce as the logging-in user, and by a technician
// double-clicking it. So every step is best-effort and independent — SYSTEM
// cannot reach a user's wallpaper, a user cannot always write the machine-wide
// key, and neither failing should stop the other.
func GenerateClearStatusScreen() string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w(`@echo off`)
	w(`rem Generated by DSKY.`)
	w(`rem Removes the imaging status screen and restores the Windows default.`)
	w(`rem`)
	w(`rem Normally nobody runs this by hand: it is registered to run at the next`)
	w(`rem startup and at the next logon, so the machine cleans itself up before`)
	w(`rem it reaches whoever it was imaged for. Run it yourself to clear the`)
	w(`rem screen now, without rebooting.`)
	w(`setlocal`)
	w(``)
	w(`rem Machine-wide lock screen. Needs administrator; the startup task has it.`)
	w(`set CSP=HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP`)
	w(`reg delete "%%CSP%%" /v LockScreenImagePath   /f >nul 2>&1`)
	w(`reg delete "%%CSP%%" /v LockScreenImageUrl    /f >nul 2>&1`)
	w(`reg delete "%%CSP%%" /v LockScreenImageStatus /f >nul 2>&1`)
	w(``)
	w(`rem The desktop lives in the user's own hive, so this half only does`)
	w(`rem anything when a person is running it - which RunOnce arranges.`)
	w(`rem`)
	w(`rem Put the Windows default back rather than blanking the value: an empty`)
	w(`rem wallpaper is a black desktop, which looks like a second fault to`)
	w(`rem whoever opens the box. If a theme is applied it reasserts its own`)
	w(`rem wallpaper anyway, so this is only the floor.`)
	w(`set DEFWALL=%%SystemRoot%%\Web\Wallpaper\Windows\img0.jpg`)
	w(`if exist "%%DEFWALL%%" (`)
	w(`  reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "%%DEFWALL%%" /f >nul 2>&1`)
	w(`) else (`)
	w(`  reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "" /f >nul 2>&1`)
	w(`)`)
	w(`rundll32.exe user32.dll, UpdatePerUserSystemParameters 1, True`)
	w(``)
	w(`rem Take the task away once it has done its job, so a machine re-imaged`)
	w(`rem later does not inherit a stale one.`)
	w(`schtasks /Delete /TN DSKYClearStatusScreen /F >nul 2>&1`)
	w(`del /q C:\ProgramData\DSKY\status.jpg >nul 2>&1`)
	w(`echo Status screen cleared.`)
	w(`endlocal`)
	return toCRLF(b.String())
}

// statusImageName is the filename the operator's success artwork is staged
// under, keeping whatever extension they gave it.
func statusImageName(s *StatusScreen) string {
	src, ref := s.SuccessImage()
	if ref != "" {
		return ref
	}
	if i := strings.LastIndexAny(src, `/\`); i >= 0 {
		return src[i+1:]
	}
	return src
}

// firstbootLog is the log name the first-boot script writes.
func firstbootLog(w *WindowsSpec) string {
	if w.Firstboot.Log != "" {
		return w.Firstboot.Log
	}
	return "firstboot.log"
}

func accountMode(w *WindowsSpec) string {
	if w.Unattend == nil {
		return ""
	}
	return w.Unattend.Vars["account_mode"]
}

// customInstallers lists the staged filenames of operator-supplied installers,
// so the check can confirm they reached the media.
func customInstallers(w *WindowsSpec, resolveRef func(string) (string, error)) []string {
	var out []string
	if resolveRef == nil {
		return out
	}
	for _, s := range w.Firstboot.Steps {
		for _, item := range []*RunItem{s.MSI, s.Exe} {
			if item == nil || item.Ref == "" {
				continue
			}
			if name, err := resolveRef(item.Ref); err == nil && name != "" {
				out = append(out, name)
			}
		}
	}
	return out
}

// editionMatch turns an ei.cfg EditionID into something Win32_OperatingSystem's
// Caption can be matched against ("Professional" reads as "Pro" there).
func editionMatch(edition string) string {
	switch edition {
	case "Professional":
		return "Pro"
	case "ProfessionalN":
		return "Pro N"
	case "Core":
		return "Home"
	}
	return edition
}

// serverEditionMatch turns an offered Server edition into something
// Win32_OperatingSystem's Caption can be matched against. Caption names the
// edition but not the installation type ("… Server 2025 Standard" either
// way), so the Core half of the choice is checked separately.
func serverEditionMatch(edition string) string {
	return strings.TrimSuffix(edition, " Core")
}

// wingetDisplayHint guesses the Add/Remove Programs name from a winget id.
// The publisher prefix is dropped and dots become spaces, which is close
// enough to match on — and a miss is reported as a failure to look at, not
// acted on.
func wingetDisplayHint(pkg string) string {
	name := pkg
	if i := strings.Index(pkg, "."); i >= 0 && i+1 < len(pkg) {
		name = pkg[i+1:]
	}
	name = strings.ReplaceAll(name, ".", " ")
	// Regex metacharacters would break the -match above.
	for _, ch := range []string{`\`, `(`, `)`, `[`, `]`, `+`, `*`, `?`, `^`, `$`, `|`, `{`, `}`} {
		name = strings.ReplaceAll(name, ch, `\`+ch)
	}
	return name
}
