package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// UserSetupName is the fixed script that applies one person's settings the
// first time they sign in, and UserSettingsName is the data it reads.
//
// Fixed script, separate data — the same shape as the app-removal pass, and
// for the same reason. A script assembled per build cannot be tested per
// build; this one is identical on every machine DSKY has ever made, and
// everything that differs is a line in a text file beside it.
const (
	UserSetupName    = "dsky-user-setup.cmd"
	UserSettingsName = "dsky-user-settings.txt"
)

// stageUserSettings leaves the per-user settings where every person who signs
// in will have them applied once, and only once.
//
// A migrated machine is a domain machine: the people who use it sign in with
// accounts this agent never sees and cannot write to. So rather than set
// anything, it leaves a script that runs at sign-in and a marker in each
// person's own profile so it does its work once and is a no-op afterwards.
func (a *Agent) stageUserSettings(actions []Action, printers []Printer, drives []MappedDrive) {
	var lines []string
	for _, act := range actions {
		if act.Method != "registry" {
			// Only a registry setting belongs to a person. Anything else in
			// this list would be a mistake in the build, and saying so is
			// better than running it as the wrong user.
			a.J.Fail(stepSettings, "%s is a %s setting and cannot be applied per user", act.Key, act.Method)
			continue
		}
		p, err := parseRegistryRef(act.Ref)
		if err != nil {
			a.J.Fail(stepSettings, "%s: %v", act.Key, err)
			continue
		}
		kind, data := "REG_DWORD", itoa(p.DWord)
		if p.String != "" {
			kind, data = "REG_SZ", p.String
		}
		lines = append(lines, strings.Join([]string{"reg", p.Path, p.Name, kind, data}, "|"))
		a.atSignIn(KindSetting, act.Key, "this belongs to a person, so it is applied when they first sign in")
	}
	for _, pr := range printers {
		lines = append(lines, strings.Join([]string{"printer", pr.SharedPath}, "|"))
		a.atSignIn(KindPrinter, pr.Name, "a queue from a print server belongs to a person, and installs its driver when they sign in")
	}
	for _, d := range drives {
		lines = append(lines, strings.Join([]string{"drive", d.Letter, d.UNC}, "|"))
		a.atSignIn(KindDrive, d.Letter+" "+d.UNC, "a mapped drive belongs to a person, and is mapped when they sign in")
	}
	if len(lines) == 0 {
		return
	}
	dataPath := filepath.Join(a.Dir, UserSettingsName)
	if err := os.WriteFile(dataPath, []byte(strings.Join(lines, "\r\n")+"\r\n"), 0o644); err != nil {
		a.J.FailDetail(stepSettings, "the per-user settings could not be written", err.Error())
		return
	}
	scriptPath := filepath.Join(a.Dir, UserSetupName)
	if err := os.WriteFile(scriptPath, []byte(userSetupScript), 0o644); err != nil {
		a.J.FailDetail(stepSettings, "the per-user setup script could not be written", err.Error())
		return
	}
	if err := a.runAtEverySignIn(scriptPath); err != nil {
		a.J.FailDetail(stepSettings, "the per-user settings will not run at sign-in", err.Error())
		return
	}
	a.J.Info(stepSettings, "%d thing(s) belong to whoever signs in, and are applied at their first sign-in", len(lines))
}

// runAtEverySignIn registers the script under the machine's Run key, which is
// every user's sign-in and not just the next one. The script's own marker
// makes it a no-op after the first time for each person.
func (a *Agent) runAtEverySignIn(script string) error {
	return a.setPolicy(policy{
		Path:   `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`,
		Name:   "DSKYUserSetup",
		String: fmt.Sprintf(`"%s"`, script),
	})
}

// userSetupScript is byte-for-byte the same on every machine.
//
// It reads dsky-user-settings.txt -- hive\path|name|type|data, one per line --
// and writes each into the signed-in user's own registry, then leaves a marker
// in that person's profile so the next sign-in does nothing. It never removes
// itself: a machine has more than one user, and the second person to sit down
// deserves the same settings as the first.
var userSetupScript = crlf(`@echo off
rem Generated by DSKY. Applies the things that belong to a person rather than
rem to the machine, once per person, at their first sign-in.
rem
rem Every line of ` + UserSettingsName + ` is kind|a|b|c, and this script is
rem the same on every machine DSKY makes.
setlocal
set "HERE=%~dp0"
set "DATA=%HERE%` + UserSettingsName + `"
set "MARK=%LOCALAPPDATA%\dsky-user-setup.done"
if exist "%MARK%" exit /b 0
if not exist "%DATA%" exit /b 0
for /f "usebackq tokens=1-5 delims=|" %%a in ("%DATA%") do call :apply "%%a" "%%b" "%%c" "%%d" "%%e"
rem Explorer reads most registry settings once, at sign-in, so restart it
rem rather than leave somebody looking at a machine that ignored half the plan.
taskkill /f /im explorer.exe >nul 2>&1
start "" explorer.exe
echo %date% %time% > "%MARK%"
exit /b 0

:apply
if /i "%~1"=="reg" reg add "%~2" /v "%~3" /t %~4 /d "%~5" /f >nul 2>&1
rem A printer connection belongs to the person, not the machine: this adds the
rem queue to their session and installs the driver from the print server.
if /i "%~1"=="printer" rundll32 printui.dll,PrintUIEntry /in /q /n "%~2" >nul 2>&1
if /i "%~1"=="drive" net use %~2 "%~3" /persistent:yes >nul 2>&1
goto :eof
`)

// crlf gives the script Windows line endings; cmd.exe is particular about
// them in a way that shows up as a script that silently does nothing.
func crlf(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r\n", "\n"), "\n", "\r\n")
}
