package compose

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/uplinkresearch/dsky/internal/agent"
	"github.com/uplinkresearch/dsky/internal/agentbin"
	"github.com/uplinkresearch/dsky/internal/drivers/catalog"
	"github.com/uplinkresearch/dsky/internal/fsimg"
	"github.com/uplinkresearch/dsky/internal/recipe"
)

// agentFirstboot is the whole of the generated first-boot batch file when the
// agent is staged: hand over and get out of the way. It stays a .cmd because
// the answer file (including copies saved in workspaces before the agent
// existed) runs firstboot.cmd by name.
const agentFirstboot = `@echo off
rem Generated by DSKY. The work is done by dsky-agent.exe, which reads
rem dsky-agent.json beside it. Edit the recipe, not this file.
"%~dp0dsky-agent.exe" apply "%~dp0."
`

// agentCovers reports whether the agent can carry out this recipe's first
// boot. It covers the three steps DSKY's own dialog writes; a recipe that
// runs its own commands, waits, or installs a payload item as a numbered
// step still gets the generated scripts, which handle those.
//
// The fallback is the point: a build that cannot use the agent produces the
// media it produced last week, not broken media.
// deferredDomainMode is what the answer file is told when the join happens at
// first boot rather than during Setup: nothing. No Provisioning element, no Credentials, no join at all --
// Setup installs Windows into a workgroup and OOBE runs on a machine that is
// not yet a domain member.
//
// agentODJ is why. Applying the blob in specialize is the obvious way round
// and it is what DSKY did, and on a machine that also has to sign itself in to
// finish provisioning it does not work. The lab machine's own OOBE log:
//
//	[Shell Unattend] UserAccounts: created account 'uplink'
//	[Shell Unattend] AutoLogon Username is 'uplink'
//	[msoobe.exe]     Not setting autologon for new local user ... domain-joined
//	[msoobe.exe]     PostTaskOperations with accountNeeded = 1
//	[taskhostw.exe]  UserOOBEController::Exit() started [2]
//	                 image state [COMPLETE] --> [SPECIALIZE_RESEAL_TO_OOBE]
//
// The answer file is honoured; msoobe then overrides the automatic sign-in
// because the machine is domain-joined, hands it to defaultuser0 to run user
// OOBE, and user OOBE cannot finish without somebody at the keyboard. The
// monitor times out and reboots back into OOBE, over and over.
//
// A by-serial batch is NOT the counter-example -- I thought it was, and it is
// worth writing down that it is not. It runs djoin in the specialize pass too
// (internal/recipe/domainserial.go), so those machines are domain members
// before OOBE starts, same as this was, and they are exposed to the same loop
// whenever they also sign themselves in. Nothing here fixes that; it is
// recorded in the plan doc as its own question.
const (
	deferredDomainMode = "deferred"
	agentODJName       = recipe.DomainBlobFile
)

func agentCovers(r *recipe.Recipe) (bool, string) {
	w := r.Windows
	if w == nil {
		return false, "not a Windows recipe"
	}
	if w.Firstboot.Mode == "template" {
		return false, "its first-boot script is a template"
	}
	for _, s := range w.Firstboot.Steps {
		switch {
		case s.Drivers, s.Debloat, s.Apps:
		case s.MSI != nil && s.MSI.Ref != "", s.Exe != nil && s.Exe.Ref != "":
			// The operator's own installers: the agent runs these itself.
		default:
			// A wait, a bare command, or an installer named by path: the
			// generated script still handles those.
			return false, "its first-boot steps include commands the agent does not run"
		}
	}
	if w.Domain != nil && !w.Domain.Offline() {
		// A credentialed join keeps the generated scripts: it is proven as it
		// stands, and its password handling is the part least worth
		// disturbing. (Joining a batch by serial number used to be the other
		// case here; it is withdrawn, and refused in recipe.DomainSpec before
		// a build gets this far.)
		return false, "it joins a domain with a username and password"
	}
	// A single offline join file is no obstacle, because with the agent in
	// charge the join no longer happens during Setup at all: the agent
	// applies it at first boot instead. See agentODJ.
	if !agentbin.Available(agentbin.AMD64) {
		return false, "this DSKY was built without the agent"
	}
	return true, ""
}

// buildManifest turns what compose already resolved into the agent's
// instructions. Nothing is decided here that was not decided by the recipe.
func buildManifest(r *recipe.Recipe, drivers recipe.ResolvedDrivers, payload []agent.Installer, verifyScript string, mig migrateParts) *agent.Manifest {
	w := r.Windows
	m := &agent.Manifest{
		Version:      agent.ManifestVersion,
		Recipe:       r.ID,
		Drivers:      agent.Drivers{Sweep: drivers.HasSweepable},
		Steps:        firstbootStepNames(r),
		VerifyScript: verifyScript,
	}
	for _, c := range drivers.Cabs {
		m.Drivers.Cabs = append(m.Drivers.Cabs, agent.Cab{File: c.File, Dir: c.Dir})
	}
	for _, e := range drivers.Extracts {
		m.Drivers.Extracts = append(m.Drivers.Extracts, agent.Extract{
			File: e.File, Dir: e.Dir, Args: e.Args, AltArgs: alternateExtract(e.Args),
		})
	}
	for _, e := range drivers.Exes {
		m.Drivers.Exes = append(m.Drivers.Exes, agent.Exe{
			File: e.File, Args: e.Args, Log: e.Log,
			OnlyVendor: e.OnlyVendor, OnlyModel: e.OnlyModel,
			TimeoutMinutes: recipe.ModelInstallerTimeoutMinutes,
		})
	}
	// Settings a migration asked for. The step goes last: a machine that is
	// still installing programs has not finished changing, and a setting
	// applied before a program that overwrites it is not a setting anybody
	// kept.
	if s := mig.Settings; s != nil && (len(s.Machine) > 0 || len(s.PerUser) > 0) {
		m.Settings = s
		m.Steps = append(m.Steps, agent.StepSettings)
	}
	if len(mig.Printers) > 0 || len(mig.Drives) > 0 {
		m.Printers, m.Drives = mig.Printers, mig.Drives
		// The settings step is what stages the per-user script, and a shared
		// queue or a mapped drive rides on it, so make sure it runs even
		// when the plan changed no settings at all.
		if m.Settings == nil {
			m.Settings = &agent.Settings{}
			m.Steps = append(m.Steps, agent.StepSettings)
		}
		for _, p := range mig.Printers {
			if !p.Shared() {
				m.Steps = append(m.Steps, agent.StepPrinters)
				break
			}
		}
	}
	if w.Domain.Offline() {
		m.Domain = &agent.Domain{File: agentODJName}
		// First, and before the programs: a machine that joins and then
		// restarts should do it before an hour of installing, not after.
		m.Steps = append([]string{agent.StepDomain}, m.Steps...)
	}
	if w.Debloat.Enabled() {
		m.Debloat = &agent.Debloat{Preset: w.Debloat.Preset, Apps: recipe.DebloatApps(w.Debloat)}
	}
	if w.Apps.Enabled() || len(payload) > 0 {
		m.Apps = &agent.Apps{Scope: recipe.AppsScope(w.Apps), Installers: payload}
		if w.Apps != nil {
			m.Apps.Winget = w.Apps.Winget
		}
	}
	return m
}

// firstbootStepNames is the recipe's step order in the agent's words.
func firstbootStepNames(r *recipe.Recipe) []string {
	var out []string
	seen := map[string]bool{}
	add := func(n string) {
		if !seen[n] {
			seen[n] = true
			out = append(out, n)
		}
	}
	for _, s := range r.Windows.Firstboot.Steps {
		switch {
		case s.Drivers:
			add("drivers")
		case s.Debloat:
			add("debloat")
		case s.Apps:
			add("apps")
		}
	}
	// The dialog always asks for programs when any were chosen, even where a
	// hand-written recipe forgot the step; match what the generated script
	// did rather than silently installing nothing.
	if r.Windows.Apps.Enabled() {
		add("apps")
	}
	return out
}

// alternateExtract is the other switch style a vendor has shipped, used when
// the configured one unpacks nothing. HP SoftPaqs took -pdf -e -s -f"dir" for
// years and current ones take /s /e /f <dir>; a pack given the wrong style
// prints its usage and exits 0.
func alternateExtract(args []string) []string {
	for _, a := range args {
		if strings.HasPrefix(a, "-") {
			return catalog.HPExtract
		}
	}
	return []string{"-pdf", "-e", "-s", `-f"{dir}"`}
}

// stageAgent puts the agent and its manifest on the media.
func stageAgent(stage fsimg.StageMap, buildTmp string, m *agent.Manifest) error {
	exe, err := agentbin.Binary(agentbin.AMD64)
	if err != nil {
		return err
	}
	// One binary for both architectures: Windows on ARM runs x64 programs,
	// and an imaging agent that takes a few seconds longer under emulation
	// is a better trade than picking the wrong one on the machine.
	exePath := filepath.Join(buildTmp, agentbin.Name)
	if err := os.WriteFile(exePath, exe, 0o755); err != nil {
		return err
	}
	stage.AddFile(exePath, path.Join(scriptsImg, agentbin.Name))

	manPath := filepath.Join(buildTmp, agent.ManifestName)
	if err := m.Save(manPath); err != nil {
		return err
	}
	stage.AddFile(manPath, path.Join(scriptsImg, agent.ManifestName))
	return nil
}

// agentInstallers lists the operator's own installers for the manifest, in
// the order the recipe runs them. They ride on the stick and need no network,
// which is why they run after the winget packages: on a machine that never
// reaches the internet, the agent that matters still lands.
func agentInstallers(w *recipe.WindowsSpec, refFiles map[string]string) []agent.Installer {
	var out []agent.Installer
	for _, s := range w.Firstboot.Steps {
		var item *recipe.RunItem
		msi := false
		switch {
		case s.MSI != nil:
			item, msi = s.MSI, true
		case s.Exe != nil:
			item = s.Exe
		default:
			continue
		}
		name := refFiles[item.Ref]
		if name == "" {
			continue
		}
		args := append([]string(nil), item.Args...)
		if item.Log != "" {
			for i, a := range args {
				args[i] = strings.ReplaceAll(a, "{log}", item.Log)
			}
		}
		out = append(out, agent.Installer{File: name, Args: args, MSI: msi})
	}
	return out
}

// AgentMedia reports whether media built from this recipe carries the agent,
// so the tool can name the right check for the machine.
func AgentMedia(r *recipe.Recipe) (bool, string) { return agentCovers(r) }

// checkJoinCanBeDeferred refuses the one recipe shape whose domain join cannot
// be moved out of Windows Setup.
//
// The join has to happen at first boot: a PC that joins a domain during Setup
// will not sign a local account in automatically afterwards, so its first boot
// never runs and it stops at a sign-in screen with no drivers and no programs.
// Whichever thing runs first boot applies it -- the agent as its first step, or
// the generated script before anything else. A hand-written first-boot script
// is neither, and DSKY will not edit a script somebody else wrote, so the build
// stops here and names the command they need rather than handing back media
// that strands the machine.
func checkJoinCanBeDeferred(r *recipe.Recipe) error {
	w := r.Windows
	if w == nil || !w.Domain.Offline() || w.Firstboot.Mode != "template" {
		return nil
	}
	return fmt.Errorf("compose: %s joins a domain and has a hand-written first-boot script "+
		"(windows.firstboot.mode: template), and those two cannot be combined. The join has to be "+
		"applied by first boot rather than by Windows Setup -- a PC that joins during Setup will not "+
		"sign a local account in automatically, so it stops at a sign-in screen with nothing "+
		"installed -- and DSKY cannot add that to a script it did not write. Either let DSKY generate "+
		"the first-boot script (windows.firstboot.mode: generate), or apply the join from your own "+
		"script with: djoin /requestodj /loadfile %%WINDIR%%\\Setup\\Scripts\\%s /windowspath "+
		"%%WINDIR%% /localos, and restart afterwards", r.ID, recipe.DomainBlobFile)
}

// migrateParts are the pieces of an approved migration plan that the agent
// carries out. They are handed to the build rather than read from the recipe:
// they belong to one machine's plan, not to a recipe somebody reuses.
type migrateParts struct {
	Settings *agent.Settings
	Printers []agent.Printer
	Drives   []agent.MappedDrive
}
