package compose

import (
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/uplinkresearch/dsky/internal/agent"
	"github.com/uplinkresearch/dsky/internal/agentbin"
	"github.com/uplinkresearch/dsky/internal/drivers/catalog"
	"github.com/uplinkresearch/dsky/internal/fsimg"
	"github.com/uplinkresearch/dsky/internal/recipe"
)

// agentFirstboot is the whole of the generated first-boot batch file when the
// agent is staged: hand over and get out of the way. It stays a .cmd because
// the answer file (including copies saved in workspaces before the agent
// existed) runs firstboot.cmd by name.
const agentFirstboot = `@echo off
rem Generated by DSKY. The work is done by dsky-agent.exe, which reads
rem dsky-agent.json beside it. Edit the recipe, not this file.
"%~dp0dsky-agent.exe" apply "%~dp0."
`

// agentCovers reports whether the agent can carry out this recipe's first
// boot. It covers the three steps DSKY's own dialog writes; a recipe that
// runs its own commands, waits, or installs a payload item as a numbered
// step still gets the generated scripts, which handle those.
//
// The fallback is the point: a build that cannot use the agent produces the
// media it produced last week, not broken media.
func agentCovers(r *recipe.Recipe) (bool, string) {
	w := r.Windows
	if w == nil {
		return false, "not a Windows recipe"
	}
	if w.Firstboot.Mode == "template" {
		return false, "its first-boot script is a template"
	}
	for _, s := range w.Firstboot.Steps {
		switch {
		case s.Drivers, s.Debloat, s.Apps:
		case s.MSI != nil && s.MSI.Ref != "", s.Exe != nil && s.Exe.Ref != "":
			// The operator's own installers: the agent runs these itself.
		default:
			// A wait, a bare command, or an installer named by path: the
			// generated script still handles those.
			return false, "its first-boot steps include commands the agent does not run"
		}
	}
	if w.Domain != nil && !w.Domain.Offline() {
		// Two joins still belong to the generated scripts, for different
		// reasons. A credentialed join is proven as it stands and its
		// password handling is the part least worth disturbing. A by-serial
		// join is reported by the generated first boot, which looks for the
		// log that dsky-domain-join.ps1 leaves when it fails; handing that
		// boot to the agent would make a failed join silent, which is worse
		// than not using the agent. The agent grows its own domain check
		// with the migration runner, and this can be revisited then.
		return false, "it joins a domain without a single join file"
	}
	// A single offline join file is no obstacle: Setup performs the join in
	// specialize, from the blob in the unattend, long before anything runs at
	// first logon, and the two never meet. This was refused for caution
	// rather than conflict, and the refusal meant every migration -- which
	// joins a domain by definition -- fell back to the generated scripts,
	// which cannot read a migration's manifest.
	if !agentbin.Available(agentbin.AMD64) {
		return false, "this DSKY was built without the agent"
	}
	return true, ""
}

// buildManifest turns what compose already resolved into the agent's
// instructions. Nothing is decided here that was not decided by the recipe.
func buildManifest(r *recipe.Recipe, drivers recipe.ResolvedDrivers, payload []agent.Installer, verifyScript string) *agent.Manifest {
	w := r.Windows
	m := &agent.Manifest{
		Version:      agent.ManifestVersion,
		Recipe:       r.ID,
		Drivers:      agent.Drivers{Sweep: drivers.HasSweepable},
		Steps:        firstbootStepNames(r),
		VerifyScript: verifyScript,
	}
	for _, c := range drivers.Cabs {
		m.Drivers.Cabs = append(m.Drivers.Cabs, agent.Cab{File: c.File, Dir: c.Dir})
	}
	for _, e := range drivers.Extracts {
		m.Drivers.Extracts = append(m.Drivers.Extracts, agent.Extract{
			File: e.File, Dir: e.Dir, Args: e.Args, AltArgs: alternateExtract(e.Args),
		})
	}
	for _, e := range drivers.Exes {
		m.Drivers.Exes = append(m.Drivers.Exes, agent.Exe{
			File: e.File, Args: e.Args, Log: e.Log,
			OnlyVendor: e.OnlyVendor, OnlyModel: e.OnlyModel,
			TimeoutMinutes: recipe.ModelInstallerTimeoutMinutes,
		})
	}
	if w.Debloat.Enabled() {
		m.Debloat = &agent.Debloat{Preset: w.Debloat.Preset, Apps: recipe.DebloatApps(w.Debloat)}
	}
	if w.Apps.Enabled() || len(payload) > 0 {
		m.Apps = &agent.Apps{Scope: recipe.AppsScope(w.Apps), Installers: payload}
		if w.Apps != nil {
			m.Apps.Winget = w.Apps.Winget
		}
	}
	return m
}

// firstbootStepNames is the recipe's step order in the agent's words.
func firstbootStepNames(r *recipe.Recipe) []string {
	var out []string
	seen := map[string]bool{}
	add := func(n string) {
		if !seen[n] {
			seen[n] = true
			out = append(out, n)
		}
	}
	for _, s := range r.Windows.Firstboot.Steps {
		switch {
		case s.Drivers:
			add("drivers")
		case s.Debloat:
			add("debloat")
		case s.Apps:
			add("apps")
		}
	}
	// The dialog always asks for programs when any were chosen, even where a
	// hand-written recipe forgot the step; match what the generated script
	// did rather than silently installing nothing.
	if r.Windows.Apps.Enabled() {
		add("apps")
	}
	return out
}

// alternateExtract is the other switch style a vendor has shipped, used when
// the configured one unpacks nothing. HP SoftPaqs took -pdf -e -s -f"dir" for
// years and current ones take /s /e /f <dir>; a pack given the wrong style
// prints its usage and exits 0.
func alternateExtract(args []string) []string {
	for _, a := range args {
		if strings.HasPrefix(a, "-") {
			return catalog.HPExtract
		}
	}
	return []string{"-pdf", "-e", "-s", `-f"{dir}"`}
}

// stageAgent puts the agent and its manifest on the media.
func stageAgent(stage fsimg.StageMap, buildTmp string, m *agent.Manifest) error {
	exe, err := agentbin.Binary(agentbin.AMD64)
	if err != nil {
		return err
	}
	// One binary for both architectures: Windows on ARM runs x64 programs,
	// and an imaging agent that takes a few seconds longer under emulation
	// is a better trade than picking the wrong one on the machine.
	exePath := filepath.Join(buildTmp, agentbin.Name)
	if err := os.WriteFile(exePath, exe, 0o755); err != nil {
		return err
	}
	stage.AddFile(exePath, path.Join(scriptsImg, agentbin.Name))

	manPath := filepath.Join(buildTmp, agent.ManifestName)
	if err := m.Save(manPath); err != nil {
		return err
	}
	stage.AddFile(manPath, path.Join(scriptsImg, agent.ManifestName))
	return nil
}

// agentInstallers lists the operator's own installers for the manifest, in
// the order the recipe runs them. They ride on the stick and need no network,
// which is why they run after the winget packages: on a machine that never
// reaches the internet, the agent that matters still lands.
func agentInstallers(w *recipe.WindowsSpec, refFiles map[string]string) []agent.Installer {
	var out []agent.Installer
	for _, s := range w.Firstboot.Steps {
		var item *recipe.RunItem
		msi := false
		switch {
		case s.MSI != nil:
			item, msi = s.MSI, true
		case s.Exe != nil:
			item = s.Exe
		default:
			continue
		}
		name := refFiles[item.Ref]
		if name == "" {
			continue
		}
		args := append([]string(nil), item.Args...)
		if item.Log != "" {
			for i, a := range args {
				args[i] = strings.ReplaceAll(a, "{log}", item.Log)
			}
		}
		out = append(out, agent.Installer{File: name, Args: args, MSI: msi})
	}
	return out
}

// AgentMedia reports whether media built from this recipe carries the agent,
// so the tool can name the right check for the machine.
func AgentMedia(r *recipe.Recipe) (bool, string) { return agentCovers(r) }
