# Generated by DSKY. Reads this computer for a migration manifest and writes
# one JSON document to standard output. Reads only: nothing is installed,
# started, stopped or written anywhere on this machine.
#
# Windows 10 ships PowerShell 5.1 and nothing newer, so this stays inside 5.1:
# no ternaries, no ?. operator, no ConvertTo-Json -AsArray, and every list is
# wrapped with @() because 5.1 turns a one-element array into a scalar and a
# zero-element array into $null.
#
# Win32_Product is never used. Enumerating it makes every installed MSI
# product reconfigure itself, which takes minutes and writes to a machine we
# promised not to touch. The uninstall registry keys hold the same list.
param(
  [switch]$AllUsers,       # load the hives of users who are not signed in
  [switch]$ProfileSizes,   # measure each profile (slow on big ones)
  [switch]$SkipStore,      # skip Get-AppxPackage, the slowest read
  [string]$UsmtPath = ""   # where scanstate.exe was supplied, if it was
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
$out = [ordered]@{}
$problems = @()

function Try-Read($what, $block) {
  try { & $block } catch { $script:problems += ("{0}: {1}" -f $what, $_.Exception.Message); $null }
}

# ---- Windows itself ---------------------------------------------------------
$out.os = Try-Read "os" {
  $cv = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"
  $build = [string]$cv.CurrentBuild
  if ($cv.PSObject.Properties.Name -contains "UBR") { $build = "$build.$($cv.UBR)" }
  $display = [string]$cv.DisplayVersion
  if (-not $display) { $display = [string]$cv.ReleaseId }
  [ordered]@{
    product_name = [string]$cv.ProductName
    build        = $build
    edition      = [string]$cv.EditionID
    arch         = $(if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64") { "x64" } elseif ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { "arm64" } else { "x86" })
    release      = $display
  }
}

# ---- the box ---------------------------------------------------------------
$out.hardware = Try-Read "hardware" {
  $cs = Get-WmiObject Win32_ComputerSystem
  $bios = Get-WmiObject Win32_BIOS
  $cpu = @(Get-WmiObject Win32_Processor)[0]
  $disks = @()
  foreach ($d in @(Get-WmiObject Win32_DiskDrive | Sort-Object Index)) {
    $disks += [ordered]@{
      index = [int]$d.Index; model = [string]$d.Model
      size_bytes = [int64]$d.Size; partitions = [int]$d.Partitions
      bus_type = [string]$d.InterfaceType
    }
  }
  [ordered]@{
    manufacturer = [string]$cs.Manufacturer
    model        = [string]$cs.Model
    serial       = [string]$bios.SerialNumber
    cpu          = [string]$cpu.Name
    ram_bytes    = [int64]$cs.TotalPhysicalMemory
    disks        = $disks
  }
}

# ---- who this machine is in the domain -------------------------------------
$out.identity = Try-Read "identity" {
  $cs = Get-WmiObject Win32_ComputerSystem
  $fqdn = ""
  $netbios = ""
  if ($cs.PartOfDomain) {
    $fqdn = [string]$cs.Domain
    $nt = @(Get-WmiObject Win32_NTDomain | Where-Object { $_.DnsForestName -or $_.DomainName })
    foreach ($d in $nt) {
      if ($d.DomainName -and $fqdn -and ($fqdn -like ("{0}*" -f $d.DomainName))) { $netbios = [string]$d.DomainName }
    }
    if (-not $netbios -and $fqdn) { $netbios = ($fqdn -split "\.")[0].ToUpper() }
  }
  # The OU the computer object is in, from the Group Policy state key: no RSAT
  # and no domain query needed, and it is what djoin /machineou wants.
  $ou = ""
  $gp = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\State\Machine"
  if (Test-Path $gp) {
    $dn = (Get-ItemProperty $gp -ErrorAction SilentlyContinue)."Distinguished-Name"
    if ($dn) {
      # CN=PC01,OU=Front Desk,DC=mead,DC=local -> everything after the CN
      $ou = ($dn -replace "^CN=[^,]+,", "")
    }
  }
  # Group memberships, if the tools happen to be here. Not an error when they
  # are not: a workstation rarely has RSAT, and the review can set the OU and
  # groups by hand.
  $groups = @()
  try {
    Import-Module ActiveDirectory -ErrorAction Stop
    $c = Get-ADComputer $env:COMPUTERNAME -Properties MemberOf -ErrorAction Stop
    foreach ($g in @($c.MemberOf)) { $groups += (($g -split ",")[0] -replace "^CN=", "") }
  } catch { }
  $local = @()
  foreach ($g in @(Get-LocalGroup -ErrorAction SilentlyContinue)) {
    $members = @()
    try {
      foreach ($mem in @(Get-LocalGroupMember -Group $g.Name -ErrorAction Stop)) { $members += [string]$mem.Name }
    } catch { }
    if ($members.Count -gt 0) { $local += [ordered]@{ name = [string]$g.Name; members = $members } }
  }
  [ordered]@{ domain_fqdn = $fqdn; domain_netbios = $netbios; ou_dn = $ou; groups = $groups; local_groups = $local }
}

# ---- installed applications ------------------------------------------------
# The uninstall keys, in all three places Windows keeps them, plus every user
# hive that is loaded (and, with -AllUsers, the ones that are not).
function Read-Uninstall($root, $arch, $who) {
  $apps = @()
  foreach ($path in @("$root\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",
                      "$root\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall")) {
    $thisArch = $arch
    if ($path -like "*WOW6432Node*") { $thisArch = "x86" }
    if (-not (Test-Path "Registry::$path")) { continue }
    foreach ($k in @(Get-ChildItem "Registry::$path" -ErrorAction SilentlyContinue)) {
      $p = $null
      try { $p = Get-ItemProperty $k.PSPath -ErrorAction Stop } catch { continue }
      $name = [string]$p.DisplayName
      if (-not $name) { continue }
      $sys = 0
      if ($p.PSObject.Properties.Name -contains "SystemComponent") { $sys = [int]$p.SystemComponent }
      $apps += [ordered]@{
        display_name     = $name
        display_version  = [string]$p.DisplayVersion
        publisher        = [string]$p.Publisher
        install_location = [string]$p.InstallLocation
        registry_key     = [string]$k.Name
        arch             = $thisArch
        source_kind      = "win32"
        system_component = ($sys -eq 1)
        user             = $who
      }
    }
  }
  return $apps
}

$out.apps = Try-Read "apps" {
  $apps = @()
  $apps += Read-Uninstall "HKEY_LOCAL_MACHINE" "x64" ""
  # Loaded user hives: everybody signed in right now.
  foreach ($sid in @(Get-ChildItem "Registry::HKEY_USERS" -ErrorAction SilentlyContinue)) {
    $name = $sid.PSChildName
    if ($name -notmatch "^S-1-5-21-" -or $name -like "*_Classes") { continue }
    $apps += Read-Uninstall "HKEY_USERS\$name" "x64" $name
  }
  # Hives that are not loaded, only when asked: this is the slow half.
  if ($AllUsers) {
    $i = 0
    foreach ($prof in @(Get-WmiObject Win32_UserProfile | Where-Object { -not $_.Special -and -not $_.Loaded })) {
      $dat = Join-Path $prof.LocalPath "NTUSER.DAT"
      if (-not (Test-Path $dat)) { continue }
      $i = $i + 1
      $key = "dsky-scan-$i"
      $loaded = $false
      try { & reg.exe load "HKU\$key" $dat 2>$null | Out-Null; $loaded = ($LASTEXITCODE -eq 0) } catch { }
      if ($loaded) {
        try { $apps += Read-Uninstall "HKEY_USERS\$key" "x64" ([string]$prof.SID) } finally {
          & reg.exe unload "HKU\$key" 2>$null | Out-Null
        }
      }
    }
  }
  # Store and packaged applications. SignatureKind tells what shipped with
  # Windows (System) from what somebody installed (Store, Enterprise).
  if (-not $SkipStore) {
    foreach ($pkg in @(Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue)) {
      $kind = "appx"
      if ($pkg.PackageFullName -like "*msix*") { $kind = "msix" }
      if ([string]$pkg.SignatureKind -eq "Store") { $kind = "store" }
      $apps += [ordered]@{
        display_name     = [string]$pkg.Name
        display_version  = [string]$pkg.Version
        publisher        = [string]$pkg.Publisher
        install_location = ""
        registry_key     = ""
        arch             = $(if ([string]$pkg.Architecture -eq "X64") { "x64" } elseif ([string]$pkg.Architecture -eq "Arm64") { "arm64" } else { "x86" })
        source_kind      = $kind
        system_component = $false
        framework        = [bool]$pkg.IsFramework
        inbox            = ([string]$pkg.SignatureKind -eq "System")
        user             = ""
      }
    }
  }
  return $apps
}

# ---- printers, drives, network ---------------------------------------------
$out.printers = Try-Read "printers" {
  $ports = @{}
  foreach ($p in @(Get-PrinterPort -ErrorAction SilentlyContinue)) {
    if ($p.PrinterHostAddress) { $ports[[string]$p.Name] = [string]$p.PrinterHostAddress }
  }
  $list = @()
  foreach ($pr in @(Get-Printer -ErrorAction SilentlyContinue)) {
    $shared = ""
    if ($pr.Type -eq "Connection" -or [string]$pr.ComputerName) {
      $shared = [string]$pr.Name
      if ($shared -notlike "\\*" -and [string]$pr.ComputerName) { $shared = "\\{0}\{1}" -f $pr.ComputerName, $pr.ShareName }
    }
    $ip = ""
    if ($ports.ContainsKey([string]$pr.PortName)) { $ip = $ports[[string]$pr.PortName] }
    $list += [ordered]@{
      name = [string]$pr.Name; driver_name = [string]$pr.DriverName
      port = [string]$pr.PortName; ip = $ip; shared_path = $shared
    }
  }
  return $list
}

$out.mapped_drives = Try-Read "mapped_drives" {
  $list = @()
  foreach ($sid in @(Get-ChildItem "Registry::HKEY_USERS" -ErrorAction SilentlyContinue)) {
    $name = $sid.PSChildName
    if ($name -notmatch "^S-1-5-21-" -or $name -like "*_Classes") { continue }
    $net = "Registry::HKEY_USERS\$name\Network"
    if (-not (Test-Path $net)) { continue }
    foreach ($letter in @(Get-ChildItem $net -ErrorAction SilentlyContinue)) {
      $p = Get-ItemProperty $letter.PSPath -ErrorAction SilentlyContinue
      if (-not $p.RemotePath) { continue }
      $who = $name
      try { $who = (New-Object System.Security.Principal.SecurityIdentifier($name)).Translate([System.Security.Principal.NTAccount]).Value } catch { }
      $list += [ordered]@{
        letter = ($letter.PSChildName.ToUpper() + ":"); unc = [string]$p.RemotePath
        persistent = $true; user = $who
      }
    }
  }
  return $list
}

$out.network = Try-Read "network" {
  $ssids = @()
  foreach ($line in @(& netsh.exe wlan show profiles 2>$null)) {
    if ($line -match ":\s*(.+)$" -and $line -match "(?i)profile") {
      $s = $matches[1].Trim()
      if ($s -and $s -ne "User profile" -and $ssids -notcontains $s) { $ssids += $s }
    }
  }
  $static = @()
  foreach ($n in @(Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object { $_.IPEnabled -and -not $_.DHCPEnabled })) {
    $addr = ""
    $prefix = 0
    if ($n.IPAddress) {
      foreach ($a in @($n.IPAddress)) { if ($a -match "^\d+\.\d+\.\d+\.\d+$" -and -not $addr) { $addr = $a } }
    }
    if ($n.IPSubnet) {
      foreach ($mask in @($n.IPSubnet)) {
        if ($mask -match "^\d+\.\d+\.\d+\.\d+$" -and $prefix -eq 0) {
          $bits = 0
          foreach ($octet in $mask.Split(".")) {
            $v = [int]$octet
            while ($v -gt 0) { if ($v -band 1) { $bits = $bits + 1 }; $v = $v -shr 1 }
          }
          $prefix = $bits
        }
      }
    }
    $gw = ""
    if ($n.DefaultIPGateway) { $gw = @($n.DefaultIPGateway)[0] }
    $dns = @()
    if ($n.DNSServerSearchOrder) { foreach ($d in @($n.DNSServerSearchOrder)) { $dns += [string]$d } }
    if ($addr) {
      $static += [ordered]@{ adapter = [string]$n.Description; address = $addr; prefix = $prefix; gateway = $gw; dns = $dns }
    }
  }
  [ordered]@{ wifi_ssids = $ssids; static_ips = $static }
}

# ---- the allowlisted settings ----------------------------------------------
function Reg-Value($path, $name) {
  if (-not (Test-Path $path)) { return $null }
  $p = Get-ItemProperty $path -ErrorAction SilentlyContinue
  if (-not $p) { return $null }
  if ($p.PSObject.Properties.Name -notcontains $name) { return $null }
  return $p.$name
}

$out.settings = Try-Read "settings" {
  $list = @()
  $add = { param($key, $value, $from) if ($null -ne $value) { $script:sList += [ordered]@{ key = $key; value = $value; from = $from } } }
  $script:sList = @()

  $scheme = (& powercfg.exe /getactivescheme 2>$null) -join " "
  & $add "power.plan" $scheme "powercfg /getactivescheme"

  # powercfg /q prints the standby timeout for AC and DC as hex seconds, in
  # that order, under the sleep subgroup.
  $q = @(& powercfg.exe /q 2>$null)
  $idx = -1
  for ($i = 0; $i -lt $q.Count; $i++) { if ($q[$i] -match "29f6c1db-86da-48c5-9fdb-f2b67b1f44da") { $idx = $i } }
  if ($idx -ge 0) {
    $acSet = $false
    for ($i = $idx; $i -lt [Math]::Min($idx + 30, $q.Count); $i++) {
      if ($q[$i] -match "Current AC Power Setting Index:\s*0x([0-9a-fA-F]+)" -and -not $acSet) {
        & $add "power.sleep_ac_minutes" ([int]("0x" + $matches[1]) / 60) "powercfg /q"
        $acSet = $true
      } elseif ($q[$i] -match "Current DC Power Setting Index:\s*0x([0-9a-fA-F]+)" -and $acSet) {
        & $add "power.sleep_dc_minutes" ([int]("0x" + $matches[1]) / 60) "powercfg /q"
        break
      }
    }
  }
  & $add "system.timezone" ((Get-TimeZone).Id) "Get-TimeZone"
  & $add "system.locale" ((Get-WinSystemLocale).Name) "Get-WinSystemLocale"
  & $add "system.region" ((Get-WinHomeLocation).GeoId) "Get-WinHomeLocation"

  $adv = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
  $hideExt = Reg-Value $adv "HideFileExt"
  if ($null -ne $hideExt) {
    $shown = 0
    if ([int]$hideExt -eq 0) { $shown = 1 }
    & $add "explorer.show_extensions" $shown "$adv\HideFileExt"
  }
  $hidden = Reg-Value $adv "Hidden"
  if ($null -ne $hidden) {
    $shownH = 0
    if ([int]$hidden -eq 1) { $shownH = 1 }
    & $add "explorer.show_hidden" $shownH "$adv\Hidden"
  }
  $mode = Reg-Value "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" "SearchboxTaskbarMode"
  if ($null -ne $mode) { & $add "taskbar.search_mode" ([int]$mode) "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search\SearchboxTaskbarMode" }
  $browser = Reg-Value "HKCU:\SOFTWARE\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice" "ProgId"
  if ($browser) { & $add "defaults.browser" ([string]$browser) "HKCU\...\UrlAssociations\http\UserChoice" }
  return $script:sList
}

# ---- profiles, and where their files are -----------------------------------
$out.profiles = Try-Read "profiles" {
  $list = @()
  foreach ($p in @(Get-WmiObject Win32_UserProfile | Where-Object { -not $_.Special })) {
    $account = [string]$p.SID
    $isLocal = $false
    try {
      $account = (New-Object System.Security.Principal.SecurityIdentifier([string]$p.SID)).Translate([System.Security.Principal.NTAccount]).Value
      if ($account -like ("{0}\*" -f $env:COMPUTERNAME)) { $isLocal = $true; $account = ".\" + ($account -split "\\")[1] }
    } catch { }
    $last = ""
    if ($p.LastUseTime) {
      try { $last = ([System.Management.ManagementDateTimeConverter]::ToDateTime($p.LastUseTime)).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ") } catch { }
    }
    $size = 0
    if ($ProfileSizes -and (Test-Path $p.LocalPath)) {
      try {
        $size = [int64](Get-ChildItem $p.LocalPath -Recurse -Force -File -ErrorAction SilentlyContinue | Measure-Object -Sum Length).Sum
      } catch { }
    }
    $list += [ordered]@{
      account = $account; profile = [string]$p.LocalPath
      last_logon = $last; size_bytes = $size; local = $isLocal
    }
  }
  return $list
}

$out.hints = Try-Read "hints" {
  $kfm = $false
  $redirected = @()
  foreach ($sid in @(Get-ChildItem "Registry::HKEY_USERS" -ErrorAction SilentlyContinue)) {
    $name = $sid.PSChildName
    if ($name -notmatch "^S-1-5-21-" -or $name -like "*_Classes") { continue }
    foreach ($acct in @("Business1", "Personal")) {
      $k = "Registry::HKEY_USERS\$name\SOFTWARE\Microsoft\OneDrive\Accounts\$acct"
      if (Test-Path $k) {
        $v = Reg-Value $k "KfmFoldersProtectedNow"
        if ($v) { $kfm = $true }
      }
    }
    $shell = "Registry::HKEY_USERS\$name\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders"
    if (Test-Path $shell) {
      $p = Get-ItemProperty $shell -ErrorAction SilentlyContinue
      foreach ($prop in @("Personal", "Desktop", "My Pictures")) {
        if ($p.PSObject.Properties.Name -contains $prop) {
          $val = [string]$p.$prop
          if ($val -like "\\\\*") { $redirected += ("{0} -> {1}" -f $prop, $val) }
        }
      }
    }
  }
  $usmt = ""
  if ($UsmtPath -and (Test-Path (Join-Path $UsmtPath "scanstate.exe"))) { $usmt = $UsmtPath }
  [ordered]@{ onedrive_kfm = $kfm; redirected_folders = $redirected; usmt_path = $usmt }
}

# ---- drivers nobody signed -------------------------------------------------
$out.unsigned_drivers = Try-Read "unsigned_drivers" {
  $list = @()
  foreach ($d in @(Get-WindowsDriver -Online -All -ErrorAction SilentlyContinue)) {
    if ([string]$d.DriverSignature -ne "Signed") {
      $list += ("{0} ({1}, {2})" -f $d.Driver, $d.ProviderName, $d.ClassName)
    }
  }
  return $list
}

$out.hostname = $env:COMPUTERNAME
$out.scanner_user = "$env:USERDOMAIN\$env:USERNAME"
$out.problems = $problems

# 5.1's ConvertTo-Json stops at two levels deep by default, which silently
# turns nested objects into type names.
$out | ConvertTo-Json -Depth 8 -Compress
